---
services:
  pyroscope:
    image: docker.io/grafana/pyroscope:2.1.0
    container_name: pyroscope-dev-2-vm-1
    ports:
      - "4040:4040"
    volumes:
      - pyroscope-data:/data
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
    attachable: true
    
volumes:
  pyroscope-data:
    driver: local

    